version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    schedule:
      interval: "daily"
      time: "21:00"
      timezone: Europe/Paris
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
      - ci
    schedule:
      interval: "daily"
      time: "21:00"
      timezone: Europe/Paris